#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later

# Os name
DE_OS="os"
# Project root Path
ROOT_PATH=$(realpath "${BASH_SOURCE%/*}"/..)
# Config Path
CONFIG_PATH="${ROOT_PATH}/config"
CONFIG_BOARDS_PATH="${CONFIG_PATH}/boards"
# Temp Path
TEMP_PATH="${ROOT_PATH}/.tmp"
# Packages Path
CONFIG_PACKAGES_PATH="${ROOT_PATH}/packages"
# Download Path
DOWNLOAD_PATH="${TEMP_PATH}/dl"
DL_STATUS_FILE_PATH="${DOWNLOAD_PATH}/.dl_file_ec_s.info"
# Source code Path
CODE_PATH="${TEMP_PATH}/code"
# Ubuntu code Path
ROOTFS_BASE_ROOT_PATH="${CODE_PATH}/ubuntu"
# Obj Path
OBJ_PATH="${TEMP_PATH}/obj"
# OS compilation intermediate path
OBJ_DE_PATH="${OBJ_PATH}/de"
# The storage path of all generated or downloaded deb packages
DEBS_PATH="${TEMP_PATH}/debs"
DBGSYM_DEBS_PATH="${TEMP_PATH}/dbgsym_debs"
# Output Path
OUTPUT_PATH="${ROOT_PATH}/output"
# Output packages Path
OUTPUT_PACKAGES_PATH="${OUTPUT_PATH}/packages"

[ -d "${TEMP_PATH}" ] || mkdir -p "${TEMP_PATH}"
[ -d "${OBJ_PATH}" ] || mkdir -p "${OBJ_PATH}"
[ -d "${OBJ_DE_PATH}" ] || mkdir -p "${OBJ_DE_PATH}"
[ -d "${DEBS_PATH}" ] || mkdir -p "${DEBS_PATH}"
[ -d "${OUTPUT_PATH}" ] || mkdir -p "${OUTPUT_PATH}"
[ -d "${OUTPUT_PACKAGES_PATH}" ] || mkdir -p "${OUTPUT_PACKAGES_PATH}"
[ -d "${DBGSYM_DEBS_PATH}" ] || mkdir -p "${DBGSYM_DEBS_PATH}"

OS_GIT_URL_CONFIG_PATH="${CONFIG_PATH}/${DE_OS}.conf"
[ -f "${OS_GIT_URL_CONFIG_PATH}" ] || {
    echo "[$ERROR] no file in ${CONFIG_PATH}/${DE_OS}.conf."
    return 1
}

source "${OS_GIT_URL_CONFIG_PATH}"

GIT_CLONE_OPTIONS="--depth=1"
MC_CPU_NUMBERS_MAX=$(grep -c processor /proc/cpuinfo)

[ -f "${CONFIG_BOARDS_PATH}/${BOARD}.conf" ] || {
    echo "[$ERROR] no file in ${CONFIG_BOARDS_PATH}/${BOARD}.conf."
    return 1
}

source "${CONFIG_BOARDS_PATH}/${BOARD}.conf"

SUPERUSER_PERMISSION="sudo -E"

# Session
# e.g: 0cd3f7a58c924d88764cac27542ba865
PROJECT_SESSION_ID=$(echo -n $(base64 </dev/urandom | head -c20) | md5sum | awk -F ' ' '{print $1}')
SESSION_PID_FILE=${TEMP_PATH}/$PROJECT_SESSION_ID.pid

# Log file(default)
DEFAULT_LOG_FIELE=${TEMP_PATH}/$PROJECT_SESSION_ID.log
